on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run the tests
        run: mvn -B test --file pom.xml
